export interface Place {
  name: string
  country: string
  flag: string
  type: "city" | "country"
}

export const PLACES: Place[] = [
  // Asia
  { name: "Tokyo", country: "Japan", flag: "🇯🇵", type: "city" },
  { name: "Osaka", country: "Japan", flag: "🇯🇵", type: "city" },
  { name: "Kyoto", country: "Japan", flag: "🇯🇵", type: "city" },
  { name: "Sapporo", country: "Japan", flag: "🇯🇵", type: "city" },
  { name: "Hiroshima", country: "Japan", flag: "🇯🇵", type: "city" },
  { name: "Seoul", country: "South Korea", flag: "🇰🇷", type: "city" },
  { name: "Busan", country: "South Korea", flag: "🇰🇷", type: "city" },
  { name: "Jeju", country: "South Korea", flag: "🇰🇷", type: "city" },
  { name: "Beijing", country: "China", flag: "🇨🇳", type: "city" },
  { name: "Shanghai", country: "China", flag: "🇨🇳", type: "city" },
  { name: "Guangzhou", country: "China", flag: "🇨🇳", type: "city" },
  { name: "Chengdu", country: "China", flag: "🇨🇳", type: "city" },
  { name: "Xi'an", country: "China", flag: "🇨🇳", type: "city" },
  { name: "Hong Kong", country: "China", flag: "🇭🇰", type: "city" },
  { name: "Macau", country: "China", flag: "🇲🇴", type: "city" },
  { name: "Bangkok", country: "Thailand", flag: "🇹🇭", type: "city" },
  { name: "Chiang Mai", country: "Thailand", flag: "🇹🇭", type: "city" },
  { name: "Phuket", country: "Thailand", flag: "🇹🇭", type: "city" },
  { name: "Pattaya", country: "Thailand", flag: "🇹🇭", type: "city" },
  { name: "Bali", country: "Indonesia", flag: "🇮🇩", type: "city" },
  { name: "Jakarta", country: "Indonesia", flag: "🇮🇩", type: "city" },
  { name: "Yogyakarta", country: "Indonesia", flag: "🇮🇩", type: "city" },
  { name: "Lombok", country: "Indonesia", flag: "🇮🇩", type: "city" },
  { name: "Singapore", country: "Singapore", flag: "🇸🇬", type: "city" },
  { name: "Kuala Lumpur", country: "Malaysia", flag: "🇲🇾", type: "city" },
  { name: "Penang", country: "Malaysia", flag: "🇲🇾", type: "city" },
  { name: "Langkawi", country: "Malaysia", flag: "🇲🇾", type: "city" },
  { name: "Manila", country: "Philippines", flag: "🇵🇭", type: "city" },
  { name: "Cebu", country: "Philippines", flag: "🇵🇭", type: "city" },
  { name: "Palawan", country: "Philippines", flag: "🇵🇭", type: "city" },
  { name: "Ho Chi Minh City", country: "Vietnam", flag: "🇻🇳", type: "city" },
  { name: "Hanoi", country: "Vietnam", flag: "🇻🇳", type: "city" },
  { name: "Da Nang", country: "Vietnam", flag: "🇻🇳", type: "city" },
  { name: "Hoi An", country: "Vietnam", flag: "🇻🇳", type: "city" },
  { name: "Phnom Penh", country: "Cambodia", flag: "🇰🇭", type: "city" },
  { name: "Siem Reap", country: "Cambodia", flag: "🇰🇭", type: "city" },
  { name: "Vientiane", country: "Laos", flag: "🇱🇦", type: "city" },
  { name: "Luang Prabang", country: "Laos", flag: "🇱🇦", type: "city" },
  { name: "Colombo", country: "Sri Lanka", flag: "🇱🇰", type: "city" },
  { name: "Kandy", country: "Sri Lanka", flag: "🇱🇰", type: "city" },
  { name: "Kathmandu", country: "Nepal", flag: "🇳🇵", type: "city" },
  { name: "Pokhara", country: "Nepal", flag: "🇳🇵", type: "city" },
  { name: "Dhaka", country: "Bangladesh", flag: "🇧🇩", type: "city" },
  { name: "Islamabad", country: "Pakistan", flag: "🇵🇰", type: "city" },
  { name: "Lahore", country: "Pakistan", flag: "🇵🇰", type: "city" },
  { name: "Karachi", country: "Pakistan", flag: "🇵🇰", type: "city" },
  { name: "Thimphu", country: "Bhutan", flag: "🇧🇹", type: "city" },
  { name: "Taipei", country: "Taiwan", flag: "🇹🇼", type: "city" },
  { name: "Tashkent", country: "Uzbekistan", flag: "🇺🇿", type: "city" },
  { name: "Samarkand", country: "Uzbekistan", flag: "🇺🇿", type: "city" },
  { name: "Almaty", country: "Kazakhstan", flag: "🇰🇿", type: "city" },
  { name: "Ulaanbaatar", country: "Mongolia", flag: "🇲🇳", type: "city" },

  // India
  { name: "Mumbai", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Delhi", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Bangalore", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Hyderabad", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Chennai", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Kolkata", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Pune", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Ahmedabad", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Jaipur", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Goa", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Varanasi", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Agra", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Udaipur", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Rishikesh", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Amritsar", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Kochi", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Mysuru", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Shimla", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Manali", country: "India", flag: "🇮🇳", type: "city" },
  { name: "Darjeeling", country: "India", flag: "🇮🇳", type: "city" },

  // Middle East
  { name: "Dubai", country: "UAE", flag: "🇦🇪", type: "city" },
  { name: "Abu Dhabi", country: "UAE", flag: "🇦🇪", type: "city" },
  { name: "Sharjah", country: "UAE", flag: "🇦🇪", type: "city" },
  { name: "Doha", country: "Qatar", flag: "🇶🇦", type: "city" },
  { name: "Riyadh", country: "Saudi Arabia", flag: "🇸🇦", type: "city" },
  { name: "Mecca", country: "Saudi Arabia", flag: "🇸🇦", type: "city" },
  { name: "Medina", country: "Saudi Arabia", flag: "🇸🇦", type: "city" },
  { name: "Jeddah", country: "Saudi Arabia", flag: "🇸🇦", type: "city" },
  { name: "Kuwait City", country: "Kuwait", flag: "🇰🇼", type: "city" },
  { name: "Muscat", country: "Oman", flag: "🇴🇲", type: "city" },
  { name: "Manama", country: "Bahrain", flag: "🇧🇭", type: "city" },
  { name: "Amman", country: "Jordan", flag: "🇯🇴", type: "city" },
  { name: "Petra", country: "Jordan", flag: "🇯🇴", type: "city" },
  { name: "Beirut", country: "Lebanon", flag: "🇱🇧", type: "city" },
  { name: "Tel Aviv", country: "Israel", flag: "🇮🇱", type: "city" },
  { name: "Jerusalem", country: "Israel", flag: "🇮🇱", type: "city" },
  { name: "Istanbul", country: "Turkey", flag: "🇹🇷", type: "city" },
  { name: "Ankara", country: "Turkey", flag: "🇹🇷", type: "city" },
  { name: "Cappadocia", country: "Turkey", flag: "🇹🇷", type: "city" },
  { name: "Antalya", country: "Turkey", flag: "🇹🇷", type: "city" },
  { name: "Tehran", country: "Iran", flag: "🇮🇷", type: "city" },

  // Europe
  { name: "London", country: "UK", flag: "🇬🇧", type: "city" },
  { name: "Edinburgh", country: "UK", flag: "🇬🇧", type: "city" },
  { name: "Manchester", country: "UK", flag: "🇬🇧", type: "city" },
  { name: "Paris", country: "France", flag: "🇫🇷", type: "city" },
  { name: "Nice", country: "France", flag: "🇫🇷", type: "city" },
  { name: "Lyon", country: "France", flag: "🇫🇷", type: "city" },
  { name: "Marseille", country: "France", flag: "🇫🇷", type: "city" },
  { name: "Berlin", country: "Germany", flag: "🇩🇪", type: "city" },
  { name: "Munich", country: "Germany", flag: "🇩🇪", type: "city" },
  { name: "Hamburg", country: "Germany", flag: "🇩🇪", type: "city" },
  { name: "Frankfurt", country: "Germany", flag: "🇩🇪", type: "city" },
  { name: "Rome", country: "Italy", flag: "🇮🇹", type: "city" },
  { name: "Milan", country: "Italy", flag: "🇮🇹", type: "city" },
  { name: "Venice", country: "Italy", flag: "🇮🇹", type: "city" },
  { name: "Florence", country: "Italy", flag: "🇮🇹", type: "city" },
  { name: "Naples", country: "Italy", flag: "🇮🇹", type: "city" },
  { name: "Amalfi", country: "Italy", flag: "🇮🇹", type: "city" },
  { name: "Barcelona", country: "Spain", flag: "🇪🇸", type: "city" },
  { name: "Madrid", country: "Spain", flag: "🇪🇸", type: "city" },
  { name: "Seville", country: "Spain", flag: "🇪🇸", type: "city" },
  { name: "Valencia", country: "Spain", flag: "🇪🇸", type: "city" },
  { name: "Ibiza", country: "Spain", flag: "🇪🇸", type: "city" },
  { name: "Granada", country: "Spain", flag: "🇪🇸", type: "city" },
  { name: "Amsterdam", country: "Netherlands", flag: "🇳🇱", type: "city" },
  { name: "Rotterdam", country: "Netherlands", flag: "🇳🇱", type: "city" },
  { name: "Brussels", country: "Belgium", flag: "🇧🇪", type: "city" },
  { name: "Bruges", country: "Belgium", flag: "🇧🇪", type: "city" },
  { name: "Vienna", country: "Austria", flag: "🇦🇹", type: "city" },
  { name: "Salzburg", country: "Austria", flag: "🇦🇹", type: "city" },
  { name: "Zurich", country: "Switzerland", flag: "🇨🇭", type: "city" },
  { name: "Geneva", country: "Switzerland", flag: "🇨🇭", type: "city" },
  { name: "Interlaken", country: "Switzerland", flag: "🇨🇭", type: "city" },
  { name: "Prague", country: "Czech Republic", flag: "🇨🇿", type: "city" },
  { name: "Brno", country: "Czech Republic", flag: "🇨🇿", type: "city" },
  { name: "Budapest", country: "Hungary", flag: "🇭🇺", type: "city" },
  { name: "Warsaw", country: "Poland", flag: "🇵🇱", type: "city" },
  { name: "Krakow", country: "Poland", flag: "🇵🇱", type: "city" },
  { name: "Gdansk", country: "Poland", flag: "🇵🇱", type: "city" },
  { name: "Lisbon", country: "Portugal", flag: "🇵🇹", type: "city" },
  { name: "Porto", country: "Portugal", flag: "🇵🇹", type: "city" },
  { name: "Algarve", country: "Portugal", flag: "🇵🇹", type: "city" },
  { name: "Athens", country: "Greece", flag: "🇬🇷", type: "city" },
  { name: "Santorini", country: "Greece", flag: "🇬🇷", type: "city" },
  { name: "Mykonos", country: "Greece", flag: "🇬🇷", type: "city" },
  { name: "Crete", country: "Greece", flag: "🇬🇷", type: "city" },
  { name: "Thessaloniki", country: "Greece", flag: "🇬🇷", type: "city" },
  { name: "Stockholm", country: "Sweden", flag: "🇸🇪", type: "city" },
  { name: "Gothenburg", country: "Sweden", flag: "🇸🇪", type: "city" },
  { name: "Copenhagen", country: "Denmark", flag: "🇩🇰", type: "city" },
  { name: "Oslo", country: "Norway", flag: "🇳🇴", type: "city" },
  { name: "Bergen", country: "Norway", flag: "🇳🇴", type: "city" },
  { name: "Helsinki", country: "Finland", flag: "🇫🇮", type: "city" },
  { name: "Reykjavik", country: "Iceland", flag: "🇮🇸", type: "city" },
  { name: "Dublin", country: "Ireland", flag: "🇮🇪", type: "city" },
  { name: "Galway", country: "Ireland", flag: "🇮🇪", type: "city" },
  { name: "Tallinn", country: "Estonia", flag: "🇪🇪", type: "city" },
  { name: "Riga", country: "Latvia", flag: "🇱🇻", type: "city" },
  { name: "Vilnius", country: "Lithuania", flag: "🇱🇹", type: "city" },
  { name: "Bucharest", country: "Romania", flag: "🇷🇴", type: "city" },
  { name: "Cluj-Napoca", country: "Romania", flag: "🇷🇴", type: "city" },
  { name: "Sofia", country: "Bulgaria", flag: "🇧🇬", type: "city" },
  { name: "Zagreb", country: "Croatia", flag: "🇭🇷", type: "city" },
  { name: "Split", country: "Croatia", flag: "🇭🇷", type: "city" },
  { name: "Dubrovnik", country: "Croatia", flag: "🇭🇷", type: "city" },
  { name: "Ljubljana", country: "Slovenia", flag: "🇸🇮", type: "city" },
  { name: "Belgrade", country: "Serbia", flag: "🇷🇸", type: "city" },
  { name: "Sarajevo", country: "Bosnia", flag: "🇧🇦", type: "city" },
  { name: "Podgorica", country: "Montenegro", flag: "🇲🇪", type: "city" },
  { name: "Skopje", country: "North Macedonia", flag: "🇲🇰", type: "city" },
  { name: "Tirana", country: "Albania", flag: "🇦🇱", type: "city" },
  { name: "Monaco", country: "Monaco", flag: "🇲🇨", type: "city" },
  { name: "Valletta", country: "Malta", flag: "🇲🇹", type: "city" },
  { name: "Nicosia", country: "Cyprus", flag: "🇨🇾", type: "city" },
  { name: "Luxembourg City", country: "Luxembourg", flag: "🇱🇺", type: "city" },
  { name: "Moscow", country: "Russia", flag: "🇷🇺", type: "city" },
  { name: "St. Petersburg", country: "Russia", flag: "🇷🇺", type: "city" },
  { name: "Kyiv", country: "Ukraine", flag: "🇺🇦", type: "city" },
  { name: "Minsk", country: "Belarus", flag: "🇧🇾", type: "city" },

  // Africa
  { name: "Cairo", country: "Egypt", flag: "🇪🇬", type: "city" },
  { name: "Alexandria", country: "Egypt", flag: "🇪🇬", type: "city" },
  { name: "Luxor", country: "Egypt", flag: "🇪🇬", type: "city" },
  { name: "Sharm el-Sheikh", country: "Egypt", flag: "🇪🇬", type: "city" },
  { name: "Nairobi", country: "Kenya", flag: "🇰🇪", type: "city" },
  { name: "Mombasa", country: "Kenya", flag: "🇰🇪", type: "city" },
  { name: "Cape Town", country: "South Africa", flag: "🇿🇦", type: "city" },
  { name: "Johannesburg", country: "South Africa", flag: "🇿🇦", type: "city" },
  { name: "Durban", country: "South Africa", flag: "🇿🇦", type: "city" },
  { name: "Marrakech", country: "Morocco", flag: "🇲🇦", type: "city" },
  { name: "Casablanca", country: "Morocco", flag: "🇲🇦", type: "city" },
  { name: "Fez", country: "Morocco", flag: "🇲🇦", type: "city" },
  { name: "Tunis", country: "Tunisia", flag: "🇹🇳", type: "city" },
  { name: "Algiers", country: "Algeria", flag: "🇩🇿", type: "city" },
  { name: "Addis Ababa", country: "Ethiopia", flag: "🇪🇹", type: "city" },
  { name: "Dar es Salaam", country: "Tanzania", flag: "🇹🇿", type: "city" },
  { name: "Zanzibar", country: "Tanzania", flag: "🇹🇿", type: "city" },
  { name: "Kampala", country: "Uganda", flag: "🇺🇬", type: "city" },
  { name: "Kigali", country: "Rwanda", flag: "🇷🇼", type: "city" },
  { name: "Lagos", country: "Nigeria", flag: "🇳🇬", type: "city" },
  { name: "Abuja", country: "Nigeria", flag: "🇳🇬", type: "city" },
  { name: "Accra", country: "Ghana", flag: "🇬🇭", type: "city" },
  { name: "Dakar", country: "Senegal", flag: "🇸🇳", type: "city" },
  { name: "Luanda", country: "Angola", flag: "🇦🇴", type: "city" },
  { name: "Lusaka", country: "Zambia", flag: "🇿🇲", type: "city" },
  { name: "Harare", country: "Zimbabwe", flag: "🇿🇼", type: "city" },
  { name: "Antananarivo", country: "Madagascar", flag: "🇲🇬", type: "city" },
  { name: "Port Louis", country: "Mauritius", flag: "🇲🇺", type: "city" },

  // Americas
  { name: "New York", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "Los Angeles", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "Chicago", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "San Francisco", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "Miami", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "Las Vegas", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "Washington DC", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "Boston", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "Seattle", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "New Orleans", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "Nashville", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "Austin", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "Denver", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "Hawaii", country: "USA", flag: "🇺🇸", type: "city" },
  { name: "Toronto", country: "Canada", flag: "🇨🇦", type: "city" },
  { name: "Vancouver", country: "Canada", flag: "🇨🇦", type: "city" },
  { name: "Montreal", country: "Canada", flag: "🇨🇦", type: "city" },
  { name: "Calgary", country: "Canada", flag: "🇨🇦", type: "city" },
  { name: "Quebec City", country: "Canada", flag: "🇨🇦", type: "city" },
  { name: "Mexico City", country: "Mexico", flag: "🇲🇽", type: "city" },
  { name: "Cancun", country: "Mexico", flag: "🇲🇽", type: "city" },
  { name: "Guadalajara", country: "Mexico", flag: "🇲🇽", type: "city" },
  { name: "Oaxaca", country: "Mexico", flag: "🇲🇽", type: "city" },
  { name: "Tulum", country: "Mexico", flag: "🇲🇽", type: "city" },
  { name: "Rio de Janeiro", country: "Brazil", flag: "🇧🇷", type: "city" },
  { name: "São Paulo", country: "Brazil", flag: "🇧🇷", type: "city" },
  { name: "Salvador", country: "Brazil", flag: "🇧🇷", type: "city" },
  { name: "Florianópolis", country: "Brazil", flag: "🇧🇷", type: "city" },
  { name: "Buenos Aires", country: "Argentina", flag: "🇦🇷", type: "city" },
  { name: "Mendoza", country: "Argentina", flag: "🇦🇷", type: "city" },
  { name: "Bariloche", country: "Argentina", flag: "🇦🇷", type: "city" },
  { name: "Santiago", country: "Chile", flag: "🇨🇱", type: "city" },
  { name: "Valparaíso", country: "Chile", flag: "🇨🇱", type: "city" },
  { name: "Lima", country: "Peru", flag: "🇵🇪", type: "city" },
  { name: "Cusco", country: "Peru", flag: "🇵🇪", type: "city" },
  { name: "Machu Picchu", country: "Peru", flag: "🇵🇪", type: "city" },
  { name: "Bogotá", country: "Colombia", flag: "🇨🇴", type: "city" },
  { name: "Medellín", country: "Colombia", flag: "🇨🇴", type: "city" },
  { name: "Cartagena", country: "Colombia", flag: "🇨🇴", type: "city" },
  { name: "Quito", country: "Ecuador", flag: "🇪🇨", type: "city" },
  { name: "Galápagos", country: "Ecuador", flag: "🇪🇨", type: "city" },
  { name: "Caracas", country: "Venezuela", flag: "🇻🇪", type: "city" },
  { name: "La Paz", country: "Bolivia", flag: "🇧🇴", type: "city" },
  { name: "Asunción", country: "Paraguay", flag: "🇵🇾", type: "city" },
  { name: "Montevideo", country: "Uruguay", flag: "🇺🇾", type: "city" },
  { name: "Panama City", country: "Panama", flag: "🇵🇦", type: "city" },
  { name: "San José", country: "Costa Rica", flag: "🇨🇷", type: "city" },
  { name: "Havana", country: "Cuba", flag: "🇨🇺", type: "city" },
  { name: "Kingston", country: "Jamaica", flag: "🇯🇲", type: "city" },
  { name: "Nassau", country: "Bahamas", flag: "🇧🇸", type: "city" },
  { name: "Bridgetown", country: "Barbados", flag: "🇧🇧", type: "city" },
  { name: "San Juan", country: "Puerto Rico", flag: "🇵🇷", type: "city" },

  // Oceania
  { name: "Sydney", country: "Australia", flag: "🇦🇺", type: "city" },
  { name: "Melbourne", country: "Australia", flag: "🇦🇺", type: "city" },
  { name: "Brisbane", country: "Australia", flag: "🇦🇺", type: "city" },
  { name: "Perth", country: "Australia", flag: "🇦🇺", type: "city" },
  { name: "Adelaide", country: "Australia", flag: "🇦🇺", type: "city" },
  { name: "Cairns", country: "Australia", flag: "🇦🇺", type: "city" },
  { name: "Gold Coast", country: "Australia", flag: "🇦🇺", type: "city" },
  { name: "Auckland", country: "New Zealand", flag: "🇳🇿", type: "city" },
  { name: "Queenstown", country: "New Zealand", flag: "🇳🇿", type: "city" },
  { name: "Christchurch", country: "New Zealand", flag: "🇳🇿", type: "city" },
  { name: "Wellington", country: "New Zealand", flag: "🇳🇿", type: "city" },
  { name: "Suva", country: "Fiji", flag: "🇫🇯", type: "city" },
  { name: "Nadi", country: "Fiji", flag: "🇫🇯", type: "city" },
  { name: "Port Moresby", country: "Papua New Guinea", flag: "🇵🇬", type: "city" },
  { name: "Papeete", country: "French Polynesia", flag: "🇵🇫", type: "city" },
  { name: "Bora Bora", country: "French Polynesia", flag: "🇵🇫", type: "city" },

  // Countries as entries too
  { name: "Japan", country: "Japan", flag: "🇯🇵", type: "country" },
  { name: "France", country: "France", flag: "🇫🇷", type: "country" },
  { name: "Italy", country: "Italy", flag: "🇮🇹", type: "country" },
  { name: "Spain", country: "Spain", flag: "🇪🇸", type: "country" },
  { name: "Germany", country: "Germany", flag: "🇩🇪", type: "country" },
  { name: "Thailand", country: "Thailand", flag: "🇹🇭", type: "country" },
  { name: "India", country: "India", flag: "🇮🇳", type: "country" },
  { name: "Indonesia", country: "Indonesia", flag: "🇮🇩", type: "country" },
  { name: "Australia", country: "Australia", flag: "🇦🇺", type: "country" },
  { name: "New Zealand", country: "New Zealand", flag: "🇳🇿", type: "country" },
  { name: "USA", country: "USA", flag: "🇺🇸", type: "country" },
  { name: "Canada", country: "Canada", flag: "🇨🇦", type: "country" },
  { name: "Brazil", country: "Brazil", flag: "🇧🇷", type: "country" },
  { name: "Morocco", country: "Morocco", flag: "🇲🇦", type: "country" },
  { name: "Egypt", country: "Egypt", flag: "🇪🇬", type: "country" },
  { name: "South Africa", country: "South Africa", flag: "🇿🇦", type: "country" },
  { name: "Greece", country: "Greece", flag: "🇬🇷", type: "country" },
  { name: "Portugal", country: "Portugal", flag: "🇵🇹", type: "country" },
  { name: "Turkey", country: "Turkey", flag: "🇹🇷", type: "country" },
  { name: "UAE", country: "UAE", flag: "🇦🇪", type: "country" },
  { name: "Vietnam", country: "Vietnam", flag: "🇻🇳", type: "country" },
  { name: "Malaysia", country: "Malaysia", flag: "🇲🇾", type: "country" },
  { name: "Philippines", country: "Philippines", flag: "🇵🇭", type: "country" },
  { name: "South Korea", country: "South Korea", flag: "🇰🇷", type: "country" },
  { name: "China", country: "China", flag: "🇨🇳", type: "country" },
  { name: "Mexico", country: "Mexico", flag: "🇲🇽", type: "country" },
  { name: "Peru", country: "Peru", flag: "🇵🇪", type: "country" },
  { name: "Colombia", country: "Colombia", flag: "🇨🇴", type: "country" },
  { name: "Argentina", country: "Argentina", flag: "🇦🇷", type: "country" },
  { name: "Kenya", country: "Kenya", flag: "🇰🇪", type: "country" },
]

export function searchPlaces(query: string, limit = 8): Place[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  return PLACES.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.country.toLowerCase().includes(q)
  ).slice(0, limit)
}
